require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BoardingDocumentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BoardingDocument. As you add validations to BoardingDocument, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoardingDocumentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all boarding_documents as @boarding_documents" do
      boarding_document = BoardingDocument.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:boarding_documents)).to eq([boarding_document])
    end
  end

  describe "GET #show" do
    it "assigns the requested boarding_document as @boarding_document" do
      boarding_document = BoardingDocument.create! valid_attributes
      get :show, {:id => boarding_document.to_param}, valid_session
      expect(assigns(:boarding_document)).to eq(boarding_document)
    end
  end

  describe "GET #new" do
    it "assigns a new boarding_document as @boarding_document" do
      get :new, {}, valid_session
      expect(assigns(:boarding_document)).to be_a_new(BoardingDocument)
    end
  end

  describe "GET #edit" do
    it "assigns the requested boarding_document as @boarding_document" do
      boarding_document = BoardingDocument.create! valid_attributes
      get :edit, {:id => boarding_document.to_param}, valid_session
      expect(assigns(:boarding_document)).to eq(boarding_document)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BoardingDocument" do
        expect {
          post :create, {:boarding_document => valid_attributes}, valid_session
        }.to change(BoardingDocument, :count).by(1)
      end

      it "assigns a newly created boarding_document as @boarding_document" do
        post :create, {:boarding_document => valid_attributes}, valid_session
        expect(assigns(:boarding_document)).to be_a(BoardingDocument)
        expect(assigns(:boarding_document)).to be_persisted
      end

      it "redirects to the created boarding_document" do
        post :create, {:boarding_document => valid_attributes}, valid_session
        expect(response).to redirect_to(BoardingDocument.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved boarding_document as @boarding_document" do
        post :create, {:boarding_document => invalid_attributes}, valid_session
        expect(assigns(:boarding_document)).to be_a_new(BoardingDocument)
      end

      it "re-renders the 'new' template" do
        post :create, {:boarding_document => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested boarding_document" do
        boarding_document = BoardingDocument.create! valid_attributes
        put :update, {:id => boarding_document.to_param, :boarding_document => new_attributes}, valid_session
        boarding_document.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested boarding_document as @boarding_document" do
        boarding_document = BoardingDocument.create! valid_attributes
        put :update, {:id => boarding_document.to_param, :boarding_document => valid_attributes}, valid_session
        expect(assigns(:boarding_document)).to eq(boarding_document)
      end

      it "redirects to the boarding_document" do
        boarding_document = BoardingDocument.create! valid_attributes
        put :update, {:id => boarding_document.to_param, :boarding_document => valid_attributes}, valid_session
        expect(response).to redirect_to(boarding_document)
      end
    end

    context "with invalid params" do
      it "assigns the boarding_document as @boarding_document" do
        boarding_document = BoardingDocument.create! valid_attributes
        put :update, {:id => boarding_document.to_param, :boarding_document => invalid_attributes}, valid_session
        expect(assigns(:boarding_document)).to eq(boarding_document)
      end

      it "re-renders the 'edit' template" do
        boarding_document = BoardingDocument.create! valid_attributes
        put :update, {:id => boarding_document.to_param, :boarding_document => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested boarding_document" do
      boarding_document = BoardingDocument.create! valid_attributes
      expect {
        delete :destroy, {:id => boarding_document.to_param}, valid_session
      }.to change(BoardingDocument, :count).by(-1)
    end

    it "redirects to the boarding_documents list" do
      boarding_document = BoardingDocument.create! valid_attributes
      delete :destroy, {:id => boarding_document.to_param}, valid_session
      expect(response).to redirect_to(boarding_documents_url)
    end
  end

end
